# Generated by Django 4.2.30 on 2026-06-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='qr_code',
            field=models.FileField(blank=True, null=True, upload_to='event_qr/'),
        ),
    ]
