# Generated by Django 5.2.15 on 2026-06-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_venue_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='form_response_count',
            field=models.PositiveIntegerField(default=0, help_text='Total registrations for this event. Auto-updated.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='google_form_url',
            field=models.URLField(blank=True, help_text='Pre-filled Google Form URL for this event. Auto-updated on save.'),
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Full submission payload.'),
        ),
    ]
