# Generated by Django 5.1.3 on 2026-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_auditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_user_id_2a1528_idx",
            old_name="core_audit_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_categor_729c0c_idx",
            old_name="core_audit_cat_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="core_auditl_action_f07419_idx",
            old_name="core_audit_act_ts_idx",
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
