# Generated by Django 5.2.15 on 2026-06-22 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_last_session_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True)),
                ('permission_level', models.PositiveSmallIntegerField(choices=[(0, 'Staff level'), (1, 'Department Head level'), (2, 'Program Manager level')], default=0, help_text='Controls which dashboard capabilities this role inherits.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('intern', 'Intern'), ('program_manager', 'Program Manager'), ('department_head', 'Department Head')], default='staff', max_length=60),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, help_text='Optional additional/custom role label. Permissions follow the built-in role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.customrole'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departments', models.ManyToManyField(blank=True, help_text='Departments involved in this program.', related_name='programs', to='accounts.department')),
                ('manager', models.ForeignKey(blank=True, limit_choices_to={'role': 'program_manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
