# Generated by Django 5.2.15 on 2026-06-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='arrival_status',
            field=models.CharField(blank=True, choices=[('early', 'Early'), ('on_time', 'On Time'), ('late', 'Late')], max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='departure_status',
            field=models.CharField(blank=True, choices=[('left_early', 'Left Early'), ('on_time', 'On Time'), ('left_late', 'Left Late')], max_length=20),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='expected_check_in_time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='expected_check_out_time',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='projectsite',
            name='grace_minutes',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
